language: clojure
dist: bionic
lein: 2.9.3
script:
  - sudo apt update
  - sudo apt install dbus-user-session curl ffmpeg
  - systemctl --user start dbus
  - export DBUS_SESSION_BUS_ADDRESS=unix:path=/run/user/$(id -u)/bus
  - mkdir ./resources/test/processes/
  - lein coverage --coveralls
  - curl -F "json_file=@target/coverage/coveralls.json" "https://coveralls.io/api/v1/jobs"
  - lein uberjar
